language: cpp
compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  matrix:
    - export NODE_VERSION="11"
    - export NODE_VERSION="10"
    - export NODE_VERSION="9"
    - export NODE_VERSION="8"
    - export NODE_VERSION="7"
    - export NODE_VERSION="6"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - git -C .nvm checkout "$(git -C .nvm describe --tags `git -C .nvm rev-list --tags --max-count=1`)"
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.9";
      export CXX="g++-4.9";
      export LINK="gcc-4.9";
      export LINKXX="g++-4.9";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION == "6" ]; then
      npm run-script coverage;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

before_deploy:
  - export RELEASE_BINDING_FILE=$(node scripts/travis-release.js)

deploy:
  provider: releases
  skip_cleanup: true
  file: "${RELEASE_BINDING_FILE}"
  api_key:
    secure: VrtFvnIa26/yCFqBBqxHV6FiSa4ERZbE1/a6wVJpsLFYKCXU1Zj9FORCL4tQKhSK7FoyiAG69NsTumKpPTBINqGSO0U8+n5YJ29Jf3BtxrrUkYjO8xHSLZLn4upcwNysCXsizUIKSZiWNw7SVB92+8xr97/Udz2ltKU7fC2mDKXPho+yGlvXSstMvO+UR+gtpUPf5WD5iWp5EAyCMFCJkpUc1233b7Vi6Aqp+7jfD6CVrOo9upXakHFu5qCmUyGbX5HTf3dV/zD+PLeeZAT86v1PS8JEpJVJxXpldy40nat8Cza9aLj5jrHF4YGyhj60ogrQd+hFVODVDaP4+NndzVrrzIy7K0plrzEV8TSRZxsI6bCYY9cCJsBJgh06Vu+SmcYrPyzWVAGwDYA+fljI4sum+hPBUQCv3WDwP+kUpQsMWzMf3lgdba5b+uGI3inX/uPFJD8LNPMeFDFrgDXNBBxlo3hh8gsy/ULGNVgvc0mw/9Sh8PTUEqMtZ3f4paCBYezqyWhumzB/swXiz6LdU211fhW9sd1g9PuuRUv7BFERkT1LQRutAHMdaO+h7LtzZYOPVLGNkoVY6WdwdW0Pd+Z7MiroFs0OV4CTY5p7PUm6E5LOKcI2VPRXlznOUYKi9qEn86Ji7I3wpWcYSuyXqasr0gIQii+VnHrmJAu3iXI=
  on:
    tags: true
    repo: bigcommerce-labs/node-sass
