-
  os: Visual Studio 2015

  branches:
    only:
      - master

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"

  build: off

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 8
      - nodejs_version: 7
      - nodejs_version: 6
      - nodejs_version: 5
      - nodejs_version: 4

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2015

  test_script: npm test

  before_deploy:
    # Save artifact with full qualified names of binding.node
    # (which we use in node-sass-binaries repo)
    - ps: Get-ChildItem .\vendor\**\*.node | % { Push-AppveyorArtifact $_.FullName -FileName (($_.FullName.Split('\\') | Select-Object -Last 2) -join '_') }


  deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      artifact: /.*binding\.node/           # upload all NuGet packages to release assets
      auth_token:
        secure: 2bD/oOwdfpSAmjd7n3m6Rpq9F+nLYd0q54pGJ1ckH+oI5Ex10SXNsF5mQobA+TfG
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only
