-
  os: Visual Studio 2015

  branches:
    only:
      - master

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"

  build: off

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 11
      - nodejs_version: 10
      - nodejs_version: 9
      - nodejs_version: 8
      - nodejs_version: 7
      - nodejs_version: 6

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2015

  test_script: npm test

  before_deploy:
    # Save artifact with full qualified names of binding.node
    # (which we use in node-sass-binaries repo)
    - ps: Get-ChildItem .\vendor\**\*.node | % { Push-AppveyorArtifact $_.FullName -FileName (($_.FullName.Split('\\') | Select-Object -Last 2) -join '_') }

  environment:
    APPVEYOR_REPO_TAG: true

  artifacts:
    - path: /.*binding\.node/

  deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      artifact: /.*binding\.node/           # upload all NuGet packages to release assets
      auth_token:
        secure: FpeVl4faEVOiFs25q8GWjWs+RiKQan55KaEFouhN60xfk4qA+tv2b8bwSwmCZQDC
      draft: false
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only