version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build-linux-node-6: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:6 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - vendor/*

  build-linux-node-8: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:8 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - vendor/*

  build-linux-node-10: # runs not using Workflows must have a `build` job as entry point
    # working_directory: ~/app
    docker: # run the steps with Docker
      - image: circleci/node:10 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - vendor/*

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: "ls ./artifacts/vendor"
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build:
    jobs:
      - build-linux-node-6:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/
      - build-linux-node-6:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/

      - publish-github-release:
          requires:
            - build-linux-node-6
            - build-linux-node-8
            - build-linux-node-10

          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/