version: 2.1


# orbs:
#   win: circleci/windows@2.4.1

commands:
  build:
    description: "Checkout, build, and test the package"
    steps:
      - checkout
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test

  release:
    description: "Generate release artifact"
    steps:
      - run:
          name: release
          command: node scripts/circle-release.js
      - persist_to_workspace:
          root: .
          paths:
            - release/*
      - store_artifacts:
          path: ./release

  install-node:
    description: "Install NVM and Node"
    parameters:
      version:
        type: integer
        default: 10
    steps:
      - run:
          name: install
          command: |
            set +e             
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            nvm install << parameters.version >>
            nvm alias default << parameters.version >>

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
jobs:

  build-linux-node-12:
    docker:
      - image: circleci/node:12
    steps:
      - build
      - release

  build-linux-node-14:
    docker:
      - image: circleci/node:14
    steps:
      - build
      - release
      - run: npm -v

  build-darwin-node-12:
    macos:
      xcode: "13.0.0"
    steps:
      - install-node:
          version: 12
      - build
      - release
  
  build-darwin-node-14:
    macos:
      xcode: "13.0.0"
    steps:
      - install-node:
          version: 14
      - build
      - release

  # npm test failing on windonws environment due to timeout even when all the tests fail
  # (note: pending tests are skipped tests)
  # 
  # build-win-node-14:
  #   executor:
  #     name: win/default
  #     size: large
  #   steps:
  #     - run: Install-Module nvm
  #     - run: nvm install 14.18.3
  #     - run: nvm use 14.18.3
  #     - run: choco install python2
  #     - build
  #     - release

  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "List Artifacts"
          command: "ls ./artifacts/release"
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${CIRCLE_CI_GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/release/

workflows:
  version: 2
  build:
    jobs:
      - build-linux-node-12:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/
      - build-linux-node-14:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/
      - build-darwin-node-12:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/
      - build-darwin-node-14:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/
      - build-win-node-14:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+$/

      - publish-github-release:
          requires:
            - build-linux-node-12
            - build-linux-node-14
            - build-darwin-node-12
            - build-darwin-node-14
            # - build-win-node-14

          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+$/
