version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build-linux-node-6: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:6 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: vendor/

  build-linux-node-8: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:8 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule
          command: git submodule update --init --recursive
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: vendor/
workflows:
  version: 2
  build:
    jobs:
      - build-linux-node-6
      - build-linux-node-8